### ISSUE TITLE
Screenshots in your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [KenoLeon/Medium-Mazes#1]
Hi there!

Saw your Medium article.  It had a nice screenshot.

Repos with screenshots are definitely going to attract visitors as it's unusual to see a GUI in a Python project.

An Animated GIF is even better.  I use ShareX to make them for documents, Issues, Tweets, etc.  They're so much smaller than any other utility I've used.

**Comment by KenoLeon** [comment]
👍

**Comment by KenoLeon** [comment]
Added a jeeeef and a bit more context, using gifbrewery cause couldn't  get into ShareX.

**Comment by PySimpleGUI** [comment]
It looks great Keno!   Very nice!  Visitors now immediately see your creation.


> couldn't get into ShareX.

I use Snagit for 99% of my captures.  I just use ShareX for the GIFs because they compact so well.  I'll take a look into gifbrewery though!
